version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/circleci-pjgram
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment: # environment variables for primary container
          BUNDLER_VERSION: 2.0.2
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: pjgram_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_PORT: 3306
          MYSQL_HOST: 127.0.0.1
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - pjgram-bundle-v2-{{ checksum "Gemfile.lock" }}
            - pjgram-bundle-v2-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: pjgram-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - pjgram-yarn-{{ checksum "yarn.lock" }}
            - pjgram-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
